# Calcoli logici

Nelle dimostrazioni matematiche (o, più in generale *logiche*) si fa spesso uso della relazione di *implicazione* che altro non è che una delle numerose relazioni *binarie* che *agiscono* su due elementi di un dato insieme $A$ e producono un risultato nell'insieme $V=\{T, F\}$, dove $T$ sta per *vero* (*True*) ed $F$ sta per *Falso* (*False*). 

A lezione abbiamo affrontato il tema delle relazioni di equivalenza ($\sim$) che, analogamente alle relazioni binarie puramente logiche, sono definite su un insieme che è il prodotto cartesiano di un insieme $A$ con sé stesso, con un risultato nell'insieme $V$: $\ \ \ \sim \ : A\times A \rightarrow V\ $; fissata una particolare relazione $\sim$ diciamo che $a,b\in A$ sono *equivalenti* se $\ \sim(a,b) \equiv a\sim b = T\in V$. Per essere di equivalenza, abbiamo visto, $\sim$ deve essere una relazione

- riflessiva: $\ \forall a\in A,\ a\sim a$
- simmetrica: $\ \forall a,b\in A, \ a\sim b \rightarrow b\sim a$
- transitiva: $\ \forall a,b,c\in A, \ a\sim b \wedge b \sim c \rightarrow a\sim c$

Vogliamo qui approfondire il tema dei calcoli logici, con particolare riguardo alla relazione di *implicazione* ($\rightarrow$). Nel caso specifico, l'insieme $A$ è quello di tutte le *proposizioni* logiche: *espressioni logiche* il cui *valore* può solo essere $T$ o $F$. Di tutte le possibili relazioni logiche dello stesso genere, quella di *implicazione* è la meno *intuitiva* nel senso che non è sempre chiaro il *perchè* della sua *tabella di verità*: l'insieme dei valori che assume per ogni coppia dell'insieme $A\times A$ di proposizioni logiche.

Il problema è affrontato utilizzando come strumento l'ambiente di programmazione Python; gli studenti non interessati ai dettagli di tipo informatico, o che non abbiano alcuna esperienza in quel linguaggio di programmazione, possono limitarsi a leggere i *risultati* presentati, sorvolando sugli aspetti tecnici legati al linguaggio e alla sua particolare implementazione nel caso specifico. 

### Valore dell'implicazione

Definiamo due variabili logiche *p* e *q* (che, nell'implementazione che segue, saranno due attributi dell'istanza *l* della classe *variable*). 

In [1]:
import numpy as np

class variable():
    def __init__(self):
        self.p=np.array([True, True, False, False])
        self.q=np.array([True, False, True, False])   
        self.neg_p=np.logical_not(self.p)
        self.neg_q=np.logical_not(self.q)
        self.ln=4
        

l=variable()

Ad esempio, se richiamiamo p (l.p):

In [2]:
l.p

array([ True,  True, False, False])

Nella classe *variable* abbiamo anche ottenuto le variabili logiche *not(p)* e *not(q)* (*l.neg_p* e *l.neg_q*, rispettivamente). Ad esempio:

In [3]:
l.neg_p

array([False, False,  True,  True])

Dobbiamo adesso preoccuparci di quali valori di verità assegnare all'*implicazione* (*imp*). L'implicazione logica è una relazione *binaria*, nel senso che *agisce* su due proposizioni logiche *p* e *q*, che viene normalmente simboleggiata dalla scrittura

$$p \rightarrow q\ \ \ \ \ \ (1)$$

e, come per ogni relazione binaria, ha un valore assegnato (vero: *true*, T, oppure falso: *false*, F) per ogni coppia di valori delle variabili *p* e *q* su cui agisce.

Poiché si tratta di una relazione binaria (agisce su esattamente 2 variabili) e ognuna delle variabili su cui agisce può assumere solo due valori (T o F), il dominio (*D*) della relazione comprende 4 possibili casi:

$$D = \{(T, T); (T, F); (F, T); (F; F)\}\nonumber$$

Per definire compiutamente la relazione di implicazione abbiamo bisogno di specificarne il valore per ogni caso appartenente al suo dominio. 

In generale, per una qualunque relazione logica binaria *R*, l'immagine di *D* sotto *R* è l'insieme $V=\{T, F\}$: 

$$R: D\rightarrow V\ \ \ \ \ (2)$$

(*R manda D in V*). Per esempio, la relazione binaria *and* (*e* logico) è definita dalle 4 assegnazioni

- *and*(T,T)=T
- *and*(T,F)=F
- *and*(F,T)=F
- *and*(F,F)=F

Queste 4 assegnazioni definiscono compiutamente la relazione *and*. Si verifichi per esercizio che l'insieme (ordinato) (T, T, T, F) sugli stessi 4 casi del dominio *D* visti per la relazione *and*, corrisponde alla relazione *or* (*o* logico).

Si verifica facilmente che esistono 16 possibili (differenti) relazioni logiche binarie, ciascuna essendo definita in base ai valori che assume sui 4 casi del dominio *D*. Infatti, *R(p,q)* può avere solo due possibili valori logici (T oppure F), e il valore che assume per ciascun caso è indipendente da quello che assume per ogni altra coppia *(p,q)* che appartiene a *D*. Le possibilità di assegnazione dei valori assunti da *R* sono dunque $2^4=16$.   

I due casi visti per *and* (T, F, F, F) e *or* (T, T, T, F) sono due delle 16 possibilità. Un'altra relazione è per esempio definita da (T, T, T, T), cioè è sempre *vera* qualunque siano i valori delle due variabili *p* e *q* su cui agisce. Una relazione simile si chiama ***tautologia***.

Dobbiamo adesso trovare un'adatta assegnazione per l'implicazione tra le 16 possibili, che sia il più possibile *aderente* a quello che, nel regionamento *logico*, intendiamo appunto con il termine *implicazione*; per esempio, l'implicazione non è normalmente intesa essere una tautologia, altrimenti ogni proposizione (logica) *implicherebbe* necessariamente la verità di ogni altra proposizione. Nello stesso modo, se assegnassimo a *imp* l'insieme (F, F, F, F) (che effettivamente è una delle 16 possibilità) non avremmo una relazione adatta a descrivere quello che intendiamo con implicazione, perchè questa sarebbe sempre *falsa* a prescindere dalle proposizioni logiche su cui agisce.  

Esistono almeno due casi in cui l'implicazione viene usata nei ragionamenti logici; si tratta di due *strumenti* spesso impiegati nelle *dimostrazioni* logiche. Uno è il ***modus ponens***

**Se *p* è *vero* *e* se *p implica q*, *allora* *q* è *vero***

Si noti che il termine ***allora*** nel costrutto di cui sopra, non è che un *sinonimo* di ***implica***; in effetti la verità di *q* è *implicata* dal fatto che *p* è vero e che *p implica q*. *Formalmente*, possiamo riformulare il *modus ponens* come:

$$p\wedge (p\rightarrow q) \rightarrow q\ \ \ \ \ (3)$$ 

dove il simbolo $\wedge$ indica la relazione logica *and*. 

Noi vogliamo che il *modus ponens* sia una *forma di ragionamento valida* (cioè sia *vera*) *indipendentemente* dai valori di verità delle proposizioni logiche *p* e *q* coinvolte nel ragionamento. In altre parole, **vogliamo che il *modus ponens* sia una tautologia**. 

Tra tutte le 16 possibilità per l'implicazione, solo alcune saranno aderenti a quello che intendiamo con la parola *implica* *e*, nel contempo, renderanno il *modus ponens* una *tautologia*. 

Nello script python che segue, ridefiniamo la classe *variable* in modo che includa una funzione (*metodo* della classe) che possa generare tutte le 16 possibili assegnazioni di una relazione binaria *R*:

In [4]:
class variable():
    def __init__(self):
        self.p=np.array([True, True, False, False])
        self.q=np.array([True, False, True, False])   
        self.neg_p=np.logical_not(self.p)
        self.neg_q=np.logical_not(self.q)
        self.ln=4
        
    def generate_tables(self):
        num=self.ln
        cases=list(range(2**self.ln))
        imp=np.array([])
        imps=np.array([])
        
        for ic in cases:
            bi=np.binary_repr(ic, num)
            imps=np.append(imps, bi)
            
        for ic in cases:
            for ip in range(4):
                imp=np.append(imp, int(imps[ic][ip]))

        imp=list(bool(imp[ic]) for ic in range(len(imp)))        
        imp=np.array(imp)
        imp=imp.reshape(2**self.ln,num)

        self.imp=imp

l=variable()
l.generate_tables()

Il metodo *generate_tables* genera tutte le 16 *tabelle di verità* delle possibili relazioni binarie *R* che agiscono su *D* [con risultato in *V*; si veda la relazione (2)]. Queste sono salvate nell'array *imp* (attributo della classe *variable*):

In [5]:
l.imp

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [False,  True,  True,  True],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

Definiamo adesso la funzione *modus_ponens* che calcola il valore di verità della proposizione (3); la funzione accetta come argomento un numero intero che varia tra 0 e 15, e identifica una delle possibili 16 righe (ciascuna di 4 valori) dell'array *imp*. 

In [6]:
def modus_ponens(it):
    
# a and (a --> b) --> b
    
    imp=l.imp[it]
    print("  p       q      p and (p --> q)     p and (p --> q) --> q")
       
    for ic in range(l.ln):
        pi=l.p[ic]
        qi=l.q[ic]
        vi=pi & imp[ic]
        
        if vi & qi: pos=0
        if vi & (not qi): pos=1
        if (not vi) and qi: pos=2
        if (not vi) and (not qi): pos=3
        
        im=imp[pos]
               
        print("%5s   %5s   %10s   %19s"  % (pi, qi, vi, im))

Per esempio, *modus_ponens(1)* restituisce:

In [7]:
modus_ponens(1)

  p       q      p and (p --> q)     p and (p --> q) --> q
 True    True        False                 False
 True   False        False                  True
False    True        False                 False
False   False        False                  True


L'ultima colonna (F,T,F,T) ci dice che, usando (F, F, F, T) come assegnazione per l'implicazione, che corrisponde alla seconda riga dell'array *imp*: 

In [8]:
l.imp[1]

array([False, False, False,  True])

l'uscita della funzione *modus_ponens* non è una tautologia (T,T,T,T). Quindi (F,F,F,T) non è una *buona* assegnazione per l'implicazione. Tutto questo a prescindere da ogni altra considerazione sull'aderenza di una simile tabella di verità al significato che diamo solitamente al termine *implica*; per esempio, se (F,F,F,T) fosse la nostra definizione di implicazione, allora sarebbe *falso* che *vero implica vero*. 

Proviamo tutte le possibilità contenute nell'array *imp* e vediamo quali di queste portino a una tautologia per il *modus ponens*: 

In [9]:
for ic in range(16):
    print("Case %2i); values:  %s" % (ic, l.imp[ic]))
    modus_ponens(ic)
    print("---------------------\n")

Case  0); values:  [False False False False]
  p       q      p and (p --> q)     p and (p --> q) --> q
 True    True        False                 False
 True   False        False                 False
False    True        False                 False
False   False        False                 False
---------------------

Case  1); values:  [False False False  True]
  p       q      p and (p --> q)     p and (p --> q) --> q
 True    True        False                 False
 True   False        False                  True
False    True        False                 False
False   False        False                  True
---------------------

Case  2); values:  [False False  True False]
  p       q      p and (p --> q)     p and (p --> q) --> q
 True    True        False                  True
 True   False        False                 False
False    True        False                  True
False   False        False                 False
---------------------

Case  3); values:  [False False

Individuiamo solo 4 casi per cui la nostra funzione *modus_ponens* restituisce (T,T,T,T), cioè una *tautologia*.

- 3:  (F, F, T, T)
- 7:  (F, T, T, T)
- 11: (T, F, T, T)
- 15: (T, T, T, T)

Notiamo che il caso 15 corrisponde a una tautologia per l'implicazione medesima (e non solo per il *modus ponens*) e quindi *non è aderente al significato logico che diamo al termine implicazione*. I casi 3 e 7 prevedono che sia *falso* che *vero implica vero*: abbiamo ancora non aderenza al significato di *implicazione*. Rimane il caso 11 (T, F, T, T) che è in effetti la *tabella di verità* usata per definire l'implicazione logica.

C'è ancora un'altra ragione che ci porta a escludere i casi 3 e 7. Si tratta di una forma di ragionamento che usiamo spesso in logica e in matematica, ed è la ***dimostrazione per assurdo***: per *dimostrare* che $p \rightarrow q$, a volte *dimostriamo* che $\neg q \rightarrow \neg p$, dove con $\neg q$ indichiamo la *negazione* di $q$ (lo stesso per $\neg p$). Se siamo in grado di dimostrare che  "**se *q* è falso *allora* deve essere falso anche *p***" usiamo questo argomento per dire che **se *p* è vero allora anche *q* deve esserlo** (appunto perché se *q* fosse falso, allora dovrebbe esserlo anche *p*, in contraddizione con la premessa che *p* sia vero). 

Noi vogliamo che le due proposizioni $(p \rightarrow q)$ e $(\neg q\rightarrow \neg p)$ siano *equivalenti*, cioè abbiano la *stessa tabella della verità*. 

Non tutte le assegnazioni per l'implicazione sono consistenti con la richiesta di cui sopra. Definiamo la funzione *absurd* come segue:  

In [10]:
def absurd(it):
    
# (p --> q) <--> (not q) --> (not p)

    imp=l.imp[it]
    
    print("  p       q      p --> q     (not q) --> (not p)")
    
    for ic in range(l.ln):
        pi=l.p[ic]
        qi=l.q[ic] 
        vi=imp[ic]
        
        qin=l.neg_q[ic]
        pin=l.neg_p[ic]
        
        if qin & pin: pos=0
        if qin & (not pin): pos=1
        if (not qin) & pin: pos=2
        if (not qin) & (not pin): pos=3
        
        im=imp[pos]
        
        print("%5s   %5s   %7s     %13s"  % (pi, qi, vi, im))

La funzione accetta come input una delle possibili *tabelle di verità* per l'implicazione (così come la precedente funzione *modus_ponens*) e calcola $\neg q \rightarrow \neg p$. Per esempio, se testiamo il caso 3 (F, F, T, T) per l'implicazione, che rendeva il *modus ponens* una tautologia, abbiamo:  

In [11]:
absurd(3)

  p       q      p --> q     (not q) --> (not p)
 True    True     False              True
 True   False     False             False
False    True      True              True
False   False      True             False


Vediamo che $p \rightarrow q$ ha valori (F, F, T, T) *diversi* da quelli di $\neg q \rightarrow \neg p$ (T, F, T, F), quindi questa assegnazione per l'implicazione rende *impossibile la dimostrazione per assurdo*. Lo stesso per il caso 7:  

In [12]:
absurd(7)

  p       q      p --> q     (not q) --> (not p)
 True    True     False              True
 True   False      True              True
False    True      True              True
False   False      True             False


Mentre per il caso 11:

In [13]:
absurd(11)

  p       q      p --> q     (not q) --> (not p)
 True    True      True              True
 True   False     False             False
False    True      True              True
False   False      True              True


vediamo che $p\rightarrow q$ è effettivamente equivalente a $\neg q\rightarrow \neg p$. 

Quindi, il caso 11 (T, F, T, T) è consistente con la *dimostrazione per assurdo* e rende il *modus ponens* una tautologia:

In [14]:
modus_ponens(11)

  p       q      p and (p --> q)     p and (p --> q) --> q
 True    True         True                  True
 True   False        False                  True
False    True        False                  True
False   False        False                  True


In definitiva, la *tabella di verità* dell'*implicazione* è:

| p   |   q   |   p --> q |
|-----|:-----:|----------:|
| T   |   T   |     T     |
| T   |   F   |     F     |
| F   |   T   |     T     |
| F   |   F   |     T     |

Nonostante le due ultime righe della tabella non siano così *intuitive* (*è vero che una premessa falsa implica una conseguenza che può essere sia vera che falsa*: ***ex falso sequitur quodlibet***) questa assegnazione è il più possibile aderente a quello che intendiamo con *implicazione* (in particolare, *è vero che una premessa vera implica una conseguenza vera* ed *è falso che una premessa vera implica una conseguenza falsa*), rende valido il *modus ponens* e rende possibile la *dimostrazione per assurdo*.